/*
 * DIO_config.h
 *
 *  Created on: Feb 8, 2020
 *      Author: Mahmoud Fawzy
 */

#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

/*
 *
 * Mode Option:
 *
 * - PRIVATE_IN_ANALOG
 * - PRIVATE_IN_FLOATING
 * - PRIVATE_IN_PULL_DOWN
 * - PRIVATE_IN_PULL_UP
 *
 * - PRIVATE_OUT_10M_PP
 * - PRIVATE_OUT_10M_OD
 * - PRIVATE_OUT_10M_AFPP
 * - PRIVATE_OUT_10M_AFOD
 *
 * - PRIVATE_OUT_2M_PP
 * - PRIVATE_OUT_2M_OD
 * - PRIVATE_OUT_2M_AFPP
 * - PRIVATE_OUT_2M_AFOD
 *
 * - PRIVATE_OUT_50M_PP
 * - PRIVATE_OUT_50M_OD
 * - PRIVATE_OUT_50M_AFPP
 * - PRIVATE_OUT_50M_AFOD
 *  */
#define DIO_PIN_0_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_1_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_2_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_3_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_4_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_5_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_6_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_7_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_8_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_9_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_10_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_11_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_12_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_13_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_14_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_15_MODE		PRIVATE_OUT_2M_PP

#define DIO_PIN_16_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_17_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_18_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_19_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_20_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_21_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_22_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_23_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_24_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_25_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_26_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_27_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_28_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_29_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_30_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_31_MODE		PRIVATE_OUT_2M_PP

#define DIO_PIN_32_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_33_MODE		PRIVATE_OUT_2M_PP
#define DIO_PIN_34_MODE		PRIVATE_OUT_2M_PP

#endif /* DIO_CONFIG_H_ */
