#ifndef FLASH_CONFIGURATION_H_
#define FLASH_CONFIGURATION_H_



#define FLASH_HALF_CYCLE_ACCESS_ENABLE			PRIVATE_DISABLE
#define FLASH_END_OF_OPERATION_INTERRUPT		PRIVATE_DISABLE
#define FLASH_ERROR_INTERRUPT					PRIVATE_DISABLE


#endif
